version: '3'

services:
  db: 
    container_name: "database"
    build: 
      context: . 
      dockerfile: ./db/db.Dockerfile
    networks:
      - default
    restart: always 
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "gocker"
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
    - /home/titan/Desktop/gocker-mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "api_web"
    build: 
      context: .
      dockerfile: ./web/api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app/